### PR TITLE
IGNORE ME -- Make home nav responsive with hamburger[Closes #40]

### LINKED ISSUE #40: Navbar disappears completely at 720 (should change to hamburger)

### PR DESCRIPTION
**Pull request by nodatall**

### CODE REVIEW

**Comment by jamestewartjr** [comment]
This one also looks fine.

**Comment by jason00111** [comment]
Nothing happens when I click on the hamburger.  The MobileMenu component is not being used.  Should these be connected?

I don’t think NavMenuButton should be renamed to NavMenuDropdown.  It really is just the button.  The dropdown itself is NavMenu.

I suggest separate css files for each component.

It looks like you’ve included the changes from your other pull request (#58) with this pull request.  Is this standard procedure?

**Comment by nodatall** [comment]
- The hamburger functionality was outside the scope of our PR. 
- We refactored the renaming: NavMenu is now NavDropdownMenu and NavMenuButton is now NavMenuDropdownButton. 
- Styling NavDropdownMenu will be a separate PR. 
- We are going to do PRs one at a time instead of 2, as to avoid duplicate changes.

**Comment by jason00111** [comment]
- The hamburger does appear so we’ll let it go on to JRob.
- We like the renaming
- We think that since you created the new HomeNavHamburger component, you should create a new css file to go along with it rather than putting the styles in home_nav.css.  It looks like you are including styling with this pull request so it seems like it’s not a separate PR.  We also think that the styling should be a part of this PR. There is not a separate issue for the styling.
- We will check this PR again about the overlapping files once PR #58 is merged.

**Pull request closed without merging**
