### PR TITLE
Install Enzyme. Resolves #50

### LINKED ISSUE #50: Setup Jest and Enzyme
As a developer, I want a test environment, so I can test :all_the_things:

### PR DESCRIPTION
**Pull request by jason00111**

### CODE REVIEW

**Comment by Anasauce** [comment]
Questions:
- Is there a new file structure for this testing framework? Or are you addressing that in later PR?
- Also how will this be integrated in the start scripts?

**Comment by jason00111** [comment]
- The file structure is already in place.  The structure for Jest which was included with create-react-app also works for Enzyme.
- The script `test` already exists (it came with create-react-app) and it will work for both Jest and Enzyme.
- Enzyme does not replace Jest.  Jest tests using snapshots (see link below) while Enzyme provides an api to do more traditional assertions.  They work well together.
If you're interested, [check this out](https://www.codementor.io/vijayst/tutorials/unit-testing-react-components-jest-or-enzyme-du1087lh8)

**Comment by Anasauce** [comment]
sounds good 👍

**Comment by jrob8577** [comment]
Love the small PR!!!!!

**Pull request merged**
