### PR TITLE
configure home routes to '/' and dashboard to '/dashboard'[closes #51]

### LINKED ISSUE #51: Configure Routes for Homepage and Dashboard

### PR DESCRIPTION
**Pull request by asantos3026**

### CODE REVIEW

**Comment by jason00111** [comment]
I reviewed this.  It looks good except the route '/dashboard' doesn't work and '/#/dashboard' does.

I suggest changing 'hashHistory' to 'browserHistory' to solve this.

**Comment by jason00111** [comment]
Looks good!

**Comment by jrob8577** [comment]
@jason00111 Great catch - I suggest putting these comments inline in the code to make it easier to have a discussion about the code in context, and to make it easier to find where a correction needs to be made. 😄

**Comment by jrob8577** [comment]
@asantos3026 @nodatall Making this change works for the routes, but it broke the display of the dashboard - it's missing the navigation bar that was there before? 
screen shot 2016-12-13 at 1 57 09 pm

**Pull request merged**
